version: '3'

services:
  rasa-nlu:
    image: rasa/rasa_nlu:0.12.3-full
    container_name: rasa-nlu
    volumes: 
      - './data/projects:/app/projects'
      - './data/logs:/app/logs'
      - './data/data:/app/data'
    expose:
      - 5000